# Generated by Django 3.0.8 on 2020-07-20 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staffinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='invited user name')),
                ('last_name', models.CharField(max_length=40, verbose_name='invited last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='invited user email')),
                ('token', models.CharField(editable=False, max_length=255, verbose_name='invite token')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='unique uuid identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='invitation created datetime')),
                ('confirmed', models.BooleanField(default=False, verbose_name='invite confirm status')),
                ('is_staff', models.BooleanField(verbose_name='is staff')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='creater of invitation')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffInvitation',
        ),
    ]
