# Generated by Django 3.0.8 on 2020-07-09 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('companies', '0002_auto_20200708_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create date ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('header', models.CharField(max_length=200, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
                ('identifier', models.CharField(default=tickets.models.get_ticket_identifer, max_length=12, unique=True, verbose_name='Ticket unique identifier')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('priorty', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=1, verbose_name='Priorty')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='companies.Company', verbose_name='Company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='companies.Department', verbose_name='Ticket department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ticket owner')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Attached user')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create date ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('content', models.TextField(verbose_name='Comment content')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment owner')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='tickets.Ticket', verbose_name='Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'commented'), ('L', 'locked'), ('U', 'unlocked'), ('O', 'opened'), ('UP', 'updated'), ('AT', 'attached')], max_length=20, verbose_name='action type')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create date')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner of activity')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
